//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easybots.AutoGeneratedCode.Licensing
{


    [global::System.SerializableAttribute()]
    public class EasybotsApplicationLicence : global::Easybots.Apps.Common.DeveloperLicence.PluginAssemblyLicence
    {

        public override byte[] DevelopmentKey
        {
            get
            {
                return new byte[] {
                        141,
                        140,
                        211,
                        21,
                        212,
                        165,
                        78,
                        173,
                        112,
                        100,
                        133,
                        125,
                        196,
                        154,
                        3,
                        224,
                        248,
                        12,
                        127,
                        184,
                        102,
                        77,
                        112,
                        70,
                        204,
                        109,
                        146,
                        118,
                        100,
                        93,
                        254,
                        78,
                        245,
                        29,
                        142,
                        158,
                        208,
                        129,
                        226,
                        61};
            }
        }

        public override byte[] PluginAssemblyKey
        {
            get
            {
                return new byte[0];
            }
        }

        public override global::System.Guid PluginAssemblyID
        {
            get
            {
                return new global::System.Guid("52735d7d-ba30-4901-b70e-300bac3f0bff");
            }
        }

        public override byte[] PluginAssemblyIDCertificate
        {
            get
            {
                return new byte[] {
                        130,
                        234,
                        189,
                        130,
                        36,
                        162,
                        234,
                        1,
                        73,
                        139,
                        197,
                        128,
                        62,
                        132,
                        66,
                        146,
                        218,
                        27,
                        30,
                        174,
                        44,
                        87,
                        104,
                        162,
                        113,
                        113,
                        196,
                        198,
                        119,
                        232,
                        60,
                        35,
                        37,
                        93,
                        132,
                        161,
                        1,
                        141,
                        58,
                        200};
            }
        }

        public override global::System.Guid EngineId
        {
            get
            {
                return new global::System.Guid("fa561b9e-1af2-485a-ac16-01cbebb28515");
            }
        }
    }
}