//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easybots.AutoGeneratedCode.Licensing
{


    [global::System.SerializableAttribute()]
    public class EasybotsApplicationLicence_152b8485cd7b484a92f25856828d9c21 : global::Easybots.Apps.Common.DeveloperLicence.PluginAssemblyLicence
    {

        public override byte[] DevelopmentKey
        {
            get
            {
                return new byte[] {
                        138,
                        229,
                        150,
                        164,
                        60,
                        25,
                        34,
                        175,
                        29,
                        138,
                        31,
                        156,
                        179,
                        138,
                        253,
                        249,
                        209,
                        163,
                        10,
                        19,
                        13,
                        247,
                        15,
                        103,
                        141,
                        123,
                        6,
                        135,
                        200,
                        39,
                        186,
                        50,
                        59,
                        178,
                        2,
                        187,
                        27,
                        239,
                        183,
                        213};
            }
        }
    }
}