//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easybots.AutoGeneratedCode.Licensing
{


    [global::System.SerializableAttribute()]
    public class EasybotsApplicationLicence : global::Easybots.Apps.Common.DeveloperLicence.PluginAssemblyLicence
    {

        public override byte[] DevelopmentKey
        {
            get
            {
                return new byte[] {
                        5,
                        118,
                        138,
                        253,
                        159,
                        96,
                        216,
                        109,
                        138,
                        186,
                        93,
                        72,
                        86,
                        6,
                        41,
                        129,
                        154,
                        59,
                        241,
                        60,
                        94,
                        54,
                        36,
                        165,
                        16,
                        126,
                        158,
                        176,
                        18,
                        15,
                        182,
                        69,
                        220,
                        162,
                        80,
                        49,
                        34,
                        193,
                        203,
                        122};
            }
        }

        public override byte[] PluginAssemblyKey
        {
            get
            {
                return new byte[0];
            }
        }

        public override global::System.Guid PluginAssemblyID
        {
            get
            {
                return new global::System.Guid("df8b81f2-74f1-4f51-b764-3aa79d049e7b");
            }
        }

        public override byte[] PluginAssemblyIDCertificate
        {
            get
            {
                return new byte[] {
                        34,
                        138,
                        69,
                        122,
                        77,
                        76,
                        119,
                        108,
                        113,
                        0,
                        223,
                        156,
                        129,
                        110,
                        15,
                        26,
                        146,
                        6,
                        93,
                        45,
                        85,
                        136,
                        186,
                        173,
                        253,
                        35,
                        155,
                        100,
                        132,
                        225,
                        59,
                        179,
                        243,
                        105,
                        211,
                        91,
                        208,
                        35,
                        198,
                        239};
            }
        }

        public override global::System.Guid EngineId
        {
            get
            {
                return new global::System.Guid("5b5bfd20-dc52-4453-acd9-0eea73095829");
            }
        }
    }
}